server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:file:/opt/h2-data/depositos-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: http://keycloak:8181/realms/tpbackend/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: swagger-ui
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/tpbackend
springdoc:
  swagger-ui:
    config-url: /api/depositos/v3/api-docs/swagger-config

service:
  osrm:
    url: http://osrm:5000
  central:
    latitud: -31.475552
    longitud: -64.118634 
    